# Generated by Django 3.2.9 on 2022-10-02 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountShelter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('about', models.TextField(blank=True, max_length=1000, null=True)),
                ('logo', models.FileField(upload_to='static/img/accounts')),
                ('director_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('requisites', models.CharField(blank=True, max_length=200, null=True)),
                ('social_network', models.CharField(blank=True, max_length=200, null=True)),
                ('number_of_animals', models.IntegerField(blank=True, null=True)),
                ('date_visits', models.DateField(blank=True, null=True)),
                ('register', models.CharField(choices=[('Отклонить', 'Отклонить'), ('Принять', 'Принять')], default='Отклонить', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LostAnimals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('breed', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=1000)),
                ('contact', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=3000)),
                ('logo', models.FileField(upload_to='static/img/companies')),
            ],
        ),
        migrations.CreateModel(
            name='ShelterNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_news', models.CharField(max_length=200)),
                ('date_news', models.DateField(auto_now_add=True)),
                ('text_news', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShelterReport',
            fields=[
                ('reports_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_report', models.CharField(max_length=200)),
                ('text_report', models.TextField(blank=True, null=True)),
                ('file_report', models.FileField(upload_to='static/uploads/files/reports')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('comment', models.TextField(blank=True, null=True)),
                ('summ', models.FloatField(max_length=200)),
                ('summ_now', models.FloatField(blank=True, max_length=200, null=True)),
                ('summ_persent', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/img/cardsAnimal')),
                ('video', models.FileField(blank=True, null=True, upload_to='static/video/cardsAnimal')),
                ('status', models.CharField(choices=[('В приюте', 'В приюте'), ('Забрали', 'Забрали'), ('Не опреденно', 'Не опреденно')], max_length=200)),
                ('breed', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('choice_shelter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.accountshelter')),
            ],
        ),
        migrations.AddField(
            model_name='accountshelter',
            name='news',
            field=models.ManyToManyField(to='Main.ShelterNews'),
        ),
        migrations.AddField(
            model_name='accountshelter',
            name='reports',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.shelterreport'),
        ),
    ]
