# Generated by Django 3.2.9 on 2022-10-21 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelterreport',
            name='company_report',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('В приюте', 'В приюте'), ('Забрали', 'Забрали'), ('Не опреденно', 'Не опреденно'), ('Архив', 'Архив')], max_length=200),
        ),
    ]
