# Generated by Django 3.2.9 on 2022-10-02 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelterreport',
            old_name='reports_id',
            new_name='id',
        ),
    ]
