# Generated by Django 3.2.9 on 2022-10-02 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_rename_reports_id_shelterreport_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountshelter',
            name='reports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.shelterreport'),
        ),
    ]
