# Generated by Django 3.2.9 on 2022-10-02 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_accountshelter_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountshelter',
            name='reports',
        ),
    ]
