# Generated by Django 3.2.9 on 2022-10-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20221022_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountshelter',
            name='date_visits',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
