# Generated by Django 3.2.9 on 2022-10-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_accountshelter_date_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='gender',
            field=models.CharField(blank=True, choices=[('Девочка', 'Девочка'), ('Мальчик', 'Мальчик')], max_length=10, null=True),
        ),
    ]
