# Generated by Django 3.2.9 on 2022-10-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_collection_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountshelter',
            name='news',
            field=models.ManyToManyField(blank=True, null=True, to='Main.ShelterNews'),
        ),
    ]
