# Generated by Django 3.2.9 on 2022-10-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_accountshelter_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountshelter',
            name='number_of_animals',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
