# Generated by Django 3.2.9 on 2022-10-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_accountshelter_number_of_animals'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='accountshelter',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='static/img/accounts'),
        ),
        migrations.AlterField(
            model_name='lostanimals',
            name='breed',
            field=models.CharField(blank=True, default='Без породы', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lostanimals',
            name='description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='lostanimals',
            name='photo',
            field=models.FileField(upload_to='static/img/lostAnimals'),
        ),
    ]
