# Generated by Django 3.2.9 on 2022-10-27 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_takeanimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_take',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.takeanimal'),
        ),
    ]
