# Generated by Django 3.2.9 on 2022-10-29 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_lostanimals_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelteHotReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hot', models.CharField(max_length=200)),
                ('text_hot', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='accountshelter',
            name='hotReport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.sheltehotreport'),
        ),
    ]
