# Generated by Django 3.2.9 on 2022-10-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_auto_20221030_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountshelter',
            name='hotReport',
        ),
        migrations.AddField(
            model_name='accountshelter',
            name='hotReport',
            field=models.ManyToManyField(blank=True, null=True, to='Main.ShelteHotReport'),
        ),
    ]
