# Generated by Django 3.2.9 on 2022-10-29 21:27

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        ('Main', '0014_auto_20221030_0248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShelteHotReport',
            new_name='ShelterHotReport',
        ),
    ]
