# Generated by Django 3.2.9 on 2022-11-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_auto_20221106_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountshelter',
            name='number_of_animals',
            field=models.IntegerField(default=0),
        ),
    ]
