# Generated by Django 3.2.9 on 2022-11-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_alter_accountshelter_number_of_animals'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalreport',
            name='report_animal',
            field=models.CharField(default=12, max_length=200),
            preserve_default=False,
        ),
    ]
