# Generated by Django 3.2.9 on 2022-11-08 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_animalreport_report_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalreport',
            name='date_animal',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
