# Generated by Django 3.2.9 on 2022-11-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_animalreport_date_animal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountshelter',
            options={'verbose_name': 'Личный кабинет приюта', 'verbose_name_plural': 'Личные кабинеты приютов'},
        ),
        migrations.AlterModelOptions(
            name='animalreport',
            options={'verbose_name': 'Отчет питомца', 'verbose_name_plural': 'Отчеты питомцев'},
        ),
        migrations.AlterModelOptions(
            name='chatlogin',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чат'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Питомец', 'verbose_name_plural': 'Питомцы'},
        ),
        migrations.AlterModelOptions(
            name='lostanimals',
            options={'verbose_name': 'Потерянное животное', 'verbose_name_plural': 'Потерянные животные'},
        ),
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.AlterModelOptions(
            name='shelterhotreport',
            options={'verbose_name': 'Срочное сообщение', 'verbose_name_plural': 'Срочные сообщения'},
        ),
        migrations.AlterModelOptions(
            name='shelternews',
            options={'verbose_name': 'Новости приюта', 'verbose_name_plural': 'Новости приютов'},
        ),
        migrations.AlterModelOptions(
            name='shelterreport',
            options={'verbose_name': 'Отчеты приюта', 'verbose_name_plural': 'Отчеты приютов'},
        ),
        migrations.AlterModelOptions(
            name='takeanimal',
            options={'verbose_name': 'Забрать питомца', 'verbose_name_plural': 'Забрать питомцев'},
        ),
        migrations.AlterField(
            model_name='accountshelter',
            name='number_of_animals',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
