# Generated by Django 3.2.9 on 2022-11-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_auto_20221108_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountshelter',
            name='number_of_animals',
            field=models.IntegerField(default=0),
        ),
    ]
