# Generated by Django 3.2.9 on 2022-11-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0021_alter_accountshelter_number_of_animals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='static/img/cardsAnimal'),
        ),
    ]
