# Generated by Django 3.2.9 on 2022-11-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0023_alter_accountshelter_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=200)),
                ('email_user', models.CharField(max_length=200, unique=True)),
                ('password_user', models.CharField(max_length=200)),
                ('register_user', models.CharField(choices=[('Отклонить', 'Отклонить'), ('Принять', 'Принять')], default='Отклонить', max_length=10)),
            ],
            options={
                'verbose_name': 'Личный кабинет пользователей',
                'verbose_name_plural': 'Личный кабинет пользователя',
            },
        ),
    ]
