# Generated by Django 3.2.9 on 2022-11-17 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0024_accountuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountuser',
            name='id',
        ),
        migrations.AddField(
            model_name='accountuser',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
