# Generated by Django 3.2.9 on 2022-11-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0025_auto_20221117_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='key',
            field=models.CharField(default='<function uuid4 at 0x000001817CB0', max_length=10, primary_key=True, serialize=False),
        ),
    ]
