# Generated by Django 3.2.9 on 2022-11-17 14:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0026_alter_accountuser_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
