# Generated by Django 3.2.9 on 2022-11-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0028_alter_accountuser_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='email_user',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
