# Generated by Django 3.2.9 on 2022-11-17 15:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0029_alter_accountuser_email_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='key',
            field=models.CharField(default=uuid.uuid4, max_length=50),
        ),
    ]
