# Generated by Django 3.2.9 on 2022-11-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0030_auto_20221117_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='key_used',
            field=models.IntegerField(default=2, max_length=2),
        ),
    ]
