# Generated by Django 3.2.9 on 2022-11-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0031_accountuser_key_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='heped_animals',
            field=models.ManyToManyField(blank=True, null=True, to='Main.Collection'),
        ),
    ]
