# Generated by Django 3.2.9 on 2022-11-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0034_accountuser_key_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountuser',
            name='key_last_update',
        ),
    ]
