# Generated by Django 3.2.9 on 2022-12-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0038_auto_20221130_0218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collection',
            new_name='AnimalCard',
        ),
    ]
