# Generated by Django 3.2.9 on 2022-12-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0039_rename_collection_animalcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelteraccount',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
