# Generated by Django 3.2.9 on 2022-12-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0041_auto_20221206_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelteraccount',
            name='requisites',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
