# Generated by Django 3.2.9 on 2022-12-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0042_alter_shelteraccount_requisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelteraccount',
            name='about',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
